### ISSUE TITLE
Real Data

### ISSUE THREAD

**Issue by XingyuLu206** [SCIR-HI/ArtificiallyR2R#2]
In the Molecule Retrieval part of subsection 3.2, you mentioned a set of annotated captions with  37,898 molecules, have you tried the performance of Ada-T5 trained with these molecules? Or is it possible to provide PubChem ID of these moelcules?

**Comment by Imsovegetable** [comment]
We indeed tried it and found its performance comparable to models with a similar amount of pseudo data (about 30k to 50k), though inferior to those utilizing more pseudo data. Unfortunately, during data cleanup, we did not retain the PubChem IDs of these molecules; we only preserved their canonical SMILES representations.

**Comment by XingyuLu206** [comment]
Thank you very much for your annoucement! I wonder some details about ada-t5. 
1. Take ada-t5-128k as an example, how are these 128 k samples selected? Do you randomly choose 128k from total 1m data?
2. Is the final performance of ada-t5 comes from pre-training with all pseudo data? Since the reported performance is slightly higher than ada-t5-512k.

**Comment by Imsovegetable** [comment]
> Take ada-t5-128k as an example, how are these 128 k samples selected? Do you randomly choose 128k from total 1m data?

Indeed, the selection process uses the `random.sample()` function from Python's random package. It's important to note that this selection process is hierarchical. Initially, a subset of 512k samples is randomly chosen from the entire 1m data. From this subset, a smaller group of 256k samples is selected. The process continues in this manner, progressively narrowing down to the final 1k samples. 

> Is the final performance of ada-t5 comes from pre-training with all pseudo data? Since the reported performance is slightly higher than ada-t5-512k.

Yes, we use all 1m data to pre-train ada-t5.
